-- 1. TABELA ITENS
-- Criada primeiro para permitir as chaves estrangeiras na tabela 'usuario'
CREATE TABLE public.itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo SMALLINT NOT NULL,
    url_imagem TEXT,
    valor_xp BIGINT DEFAULT 0
);

-- 2. TABELA USUARIO
CREATE TABLE public.usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    telefone TEXT,
    senha_hash TEXT NOT NULL,
    bio TEXT,
    xp_total BIGINT DEFAULT 0,
    nivel BIGINT DEFAULT 1,
    criado TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    id_item_chapeu BIGINT REFERENCES public.itens(id) ON DELETE SET NULL,
    id_item_mao BIGINT REFERENCES public.itens(id) ON DELETE SET NULL,
    id_item_mascote BIGINT REFERENCES public.itens(id) ON DELETE SET NULL
);

-- 3. TABELA FILMES
CREATE TABLE public.filmes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    sinopse TEXT,
    ano_lancamento DATE,
    duracao DOUBLE PRECISION,
    classificacao TEXT,
    poster_url TEXT,
    franquia TEXT
);

-- 4. TABELA COMENTARIOS
CREATE TABLE public.comentarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES public.usuario(id) ON DELETE CASCADE,
    id_filme BIGINT NOT NULL REFERENCES public.filmes(id) ON DELETE CASCADE,
    conteudo TEXT NOT NULL,
    criado TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABELA CURTIDAS
CREATE TABLE public.curtidas (
    id_usuario BIGINT NOT NULL REFERENCES public.usuario(id) ON DELETE CASCADE,
    id_comentario BIGINT NOT NULL REFERENCES public.comentarios(id) ON DELETE CASCADE,
    criado TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (id_usuario, id_comentario)
);

-- 6. TABELA AVALIACOES
CREATE TABLE public.avaliacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filme BIGINT NOT NULL REFERENCES public.filmes(id) ON DELETE CASCADE,
    id_usuario BIGINT NOT NULL REFERENCES public.usuario(id) ON DELETE CASCADE,
    nota BIGINT NOT NULL,
    CONSTRAINT uq_usuario_filme UNIQUE (id_usuario, id_filme)
);

-- 7. TABELA ELENCO
CREATE TABLE public.elenco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filme BIGINT NOT NULL REFERENCES public.filmes(id) ON DELETE CASCADE,
    ator TEXT NOT NULL,
    personagens TEXT[],
    url_img TEXT
);

-- ATIVAÇÃO DE ROW LEVEL SECURITY (RLS) RECOMENDADA NO SUPABASE
ALTER TABLE public.itens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.filmes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comentarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curtidas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.avaliacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.elenco ENABLE ROW LEVEL SECURITY;